---

- name: Create Target Schema
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - schema.yml
  vars:
    apic_host: sandboxapicdc.cisco.com
    username: admin
    password: '!v3G@!4@Y'
    validate_certs: no
    aci_services:
      - name: Active_Directory
        tenant: Tn-GISA-ENT
        vrf: Vrf-TnGISA-ENT
        bridge_domain:
          - name: Bd-TnGISA-ENT-DOMAIN
            subnets:
              - { gateway: 10.10.10.1, mask: 24 }
              - { gateway: 20.10.10.1, mask: 24 }
              - { gateway: 30.10.10.1, mask: 24 }
        app_group: Ap-TnGISA-ENT
        endpoint_group:
          - name: Epg-TnGISA-ENT-DOMAIN-AD
        security_group:
          - name: Esg-TnGISA-ENT-DOMAIN-AD
      - name: Domain Name Service
        tenant: Tn-GISA-ENT
        vrf: Vrf-TnGISA-ENT
        bridge_domain:
          - name: Bd-TnGISA-ENT-DOMAIN
            subnets:
              - { gateway: 40.10.10.1, mask: 24 }
              - { gateway: 50.10.10.1, mask: 24 }
              - { gateway: 60.10.10.1, mask: 24 }
        app_group: Ap-TnGISA-ENT
        endpoint_group:
          - name: Epg-TnGISA-ENT-DOMAIN-DNS
        security_group:
          - name: Esg-TnGISA-ENT-DOMAIN-DNS

      - name: DHCP
        tenant: Tn-GISA-ENT
        vrf: Vrf-TnGISA-ENT
        bridge_domain:
          - name: Bd-TnGISA-ENT-DOMAIN
            subnets:
              - { gateway: 70.10.10.1, mask: 24 }
              - { gateway: 80.10.10.1, mask: 24 }
              - { gateway: 90.10.10.1, mask: 24 }
        app_group: Ap-TnGISA-ENT
        endpoint_group:
          - name: Epg-TnGISA-ENT-DOMAIN-DHCP
        security_group:
          - name: Esg-TnGISA-ENT-DOMAIN-DHCP

      - name: Exchange
        tenant: Tn-GISA-ENT
        vrf: Vrf-TnGISA-ENT
        bridge_domain:
          - name: Bd-TnGISA-ENT-SERVICES
            subnets:
              - { gateway: 100.10.10.1, mask: 24 }
              - { gateway: 110.10.10.1, mask: 24 }
              - { gateway: 120.10.10.1, mask: 24 }
        app_group: Ap-TnGISA-ENT
        endpoint_group:
          - name: Epg-TnGISA-ENT-SERVICES-EXCH
        security_group:
          - name: Esg-TnGISA-ENT-SERVICES-EXCH

      - name: ACAS
        tenant: Tn-GISA-ENT
        vrf: Vrf-TnGISA-ENT
        bridge_domain:
          - name: Bd-TnGISA-ENT-ACAS
            subnets:
              - { gateway: 130.10.10.1, mask: 24 }
              - { gateway: 140.10.10.1, mask: 24 }
              - { gateway: 150.10.10.1, mask: 24 }
        app_group: Ap-TnGISA-ENT
        endpoint_group:
          - name: Epg-TnGISA-ENT-ACAS-EPO
        security_group:
          - name: Esg-TnGISA-ENT-ACAS-SENSORS

      - name: ACAS
        tenant: Tn-GISA-ENT
        vrf: Vrf-TnGISA-ENT
        bridge_domain:
          - name: Bd-TnGISA-ENT-ACAS
            subnets:
              - { gateway: 160.10.10.1, mask: 24 }
              - { gateway: 170.10.10.1, mask: 24 }
              - { gateway: 180.10.10.1, mask: 24 }
        app_group: Ap-TnGISA-ENT
        endpoint_group:
          - name: Epg-TnGISA-ENT-ACAS-EPO
        security_group:
          - name: Esg-TnGISA-ENT-ACAS-SENSORS

      - name: Network Management
        tenant: Tn-GISA-ENT
        vrf: Vrf-TnGISA-ENT
        bridge_domain:
          - name: Bd-TnGISA-ENT-NET
            subnets:
              - { gateway: 190.10.10.1, mask: 24 }
              - { gateway: 200.10.10.1, mask: 24 }
              - { gateway: 210.10.10.1, mask: 24 }
        app_group: Ap-TnGISA-ENT
        endpoint_group:
          - name: Epg-TnGISA-ENT-NET-MGMT
        security_group:
          - name: Esg-TnGISA-ENT-NET-MGMT

      - name: Network ISE
        tenant: Tn-GISA-ENT
        vrf: Vrf-TnGISA-ENT
        bridge_domain:
          - name: Bd-TnGISA-ENT-NET
            subnets:
              - { gateway: 220.10.10.1, mask: 24 }
              - { gateway: 230.10.10.1, mask: 24 }
              - { gateway: 240.10.10.1, mask: 24 }
        app_group: Ap-TnGISA-ENT
        endpoint_group:
          - name: Epg-TnGISA-ENT-NET-ISE
        security_group:
          - name: Esg-TnGISA-ENT-NET-ISE

      - name: VDI Master
        tenant: Tn-GISA-ENT
        vrf: Vrf-TnGISA-VDI
        bridge_domain:
          - name: Bd-TnGISA-ENT-VDI
            subnets:
              - { gateway: 250.10.10.1, mask: 24 }
              - { gateway: 10.20.10.1, mask: 24 }
              - { gateway: 10.30.10.1, mask: 24 }
        app_group: Ap-TnGISA-ENT
        endpoint_group:
          - name: Epg-TnGISA-ENT-VDI-MASTER
        security_group:
          - name: Esg-TnGISA-ENT-VDI-MASTER

      - name: VDI Pool
        tenant: Tn-GISA-ENT
        vrf: Vrf-TnGISA-VDI
        bridge_domain:
          - name: Bd-TnGISA-ENT-VDI
            subnets:
              - { gateway: 10.40.10.1, mask: 24 }
              - { gateway: 10.50.10.1, mask: 24 }
              - { gateway: 10.60.10.1, mask: 24 }
        app_group: Ap-TnGISA-ENT
        endpoint_group:
          - name: Epg-TnGISA-ENT-VDI-POOL
        security_group:
          - name: Esg-TnGISA-ENT-VDI-POOL

      - name: PoR1
        tenant: Tn-TnPoR1-ENT
        vrf: Vrf-TnPoR1-ENT
        bridge_domain:
          - name: Bd-TnPoR1-ENT
            subnets:
              - { gateway: 10.70.10.1, mask: 24 }
              - { gateway: 10.80.10.1, mask: 24 }
              - { gateway: 10.90.10.1, mask: 24 }
        app_group: Ap-TnPoR1-ENT
        endpoint_group:
          - name: Epg-TnPoR1-ENT
        security_group:
          - name: Esg-TnPoR1-ENT

  tasks:

    - name: Create tenant
      cisco.aci.aci_tenant:
        host: "{{ apic_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: "{{ validate_certs }}"
        tenant: "{{ tenant_name }}"
        state: present
      delegate_to: localhost
      register: tenant_result

    - name: Create VRF
      cisco.aci.aci_vrf:
        host: "{{ apic_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: "{{ validate_certs }}"
        tenant: "{{ tenant_name }}"
        vrf: "{{ vrf_name }}"
        state: present
      delegate_to: localhost
      register: vrf_result

    - name: Create Bridge Domain
      cisco.aci.aci_bd:
        host: "{{ apic_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: "{{ validate_certs }}"
        tenant: "{{ tenant_name }}"
        bd: "{{ item.name }}"
        vrf: "{{ vrf_name }}"
        arp_flooding: false
        enable_routing: true
        state: present
      delegate_to: localhost
      loop: "{{ bridge_domains }}"

    - name: Add all subnets to each Bridge Domain
      cisco.aci.aci_bd_subnet:
        host: "{{ apic_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: "{{ validate_certs }}"
        tenant: "{{ tenant_name }}"
        bd: "{{ item.0.name }}"
        gateway: "{{ item.1.gateway }}"
        mask: "{{ item.1.mask }}"
        scope: "private"
        state: present
      delegate_to: localhost
      loop: "{{ bridge_domains | subelements('subnets') }}"
    
    - name: Create Application Profile
      cisco.aci.aci_ap:
        host: "{{ apic_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: "{{ validate_certs }}"
        tenant: "{{ tenant_name }}"
        app_profile: "{{ ap_name }}"
        description: "App Profile for Enterprise Services"
        state: present
      delegate_to: localhost

    - name: Create Application EPG
      cisco.aci.aci_epg:
        host: "{{ apic_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: "{{ validate_certs }}"
        tenant: "{{ tenant_name }}"
        ap: "{{ ap_name }}"
        epg: "duplication_test"
        bd: "Enterprise_Services"
        state: present
      delegate_to: localhost